# Generated by Django 4.1.5 on 2023-01-30 14:37

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contacto')),
                ('messagge', models.TextField(verbose_name='Mensaje')),
            ],
            options={
                'verbose_name_plural': 'Contactos',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title_page', models.CharField(max_length=100, verbose_name='Titulo de la pagina')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Encabezado')),
                ('subtitle', models.CharField(blank=True, max_length=50, null=True, verbose_name='SubEncabezado')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('title_sec1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Titulo secc 1')),
                ('title_sec2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Titulo secc 2')),
                ('title_sec3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Titulo secc 3')),
                ('title_sec4', models.CharField(blank=True, max_length=50, null=True, verbose_name='Titulo secc 4')),
                ('title_sec5', models.CharField(blank=True, max_length=50, null=True, verbose_name='Titulo secc 5')),
                ('about_text', models.TextField(blank=True, null=True, verbose_name='Acerca de')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=10, verbose_name='Telefono')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Direccion')),
                ('horario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Horario')),
                ('logo_principal', models.ImageField(blank=True, null=True, upload_to='home')),
                ('logo_secundario', models.ImageField(blank=True, null=True, upload_to='home')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Portada')),
            ],
            options={
                'verbose_name_plural': 'Home',
            },
        ),
        migrations.CreateModel(
            name='Suscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de suscriptor')),
            ],
            options={
                'verbose_name_plural': 'Suscriptores',
            },
        ),
    ]
