# Generated by Django 4.1.5 on 2023-01-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
