# Generated by Django 4.1.5 on 2023-01-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='face',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='home',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Inatagram'),
        ),
        migrations.AddField(
            model_name='home',
            name='tiktok',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='tiktok'),
        ),
        migrations.AddField(
            model_name='home',
            name='youtube',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='youtube'),
        ),
        migrations.AlterField(
            model_name='home',
            name='about_text',
            field=models.TextField(blank=True, null=True, verbose_name='Acerca de nosotros'),
        ),
    ]
