# Generated by Django 4.1.5 on 2023-01-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_home_face_home_instagram_home_tiktok_home_youtube_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='face',
        ),
        migrations.RemoveField(
            model_name='home',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='home',
            name='tiktok',
        ),
        migrations.RemoveField(
            model_name='home',
            name='youtube',
        ),
        migrations.AddField(
            model_name='home',
            name='link_red_social1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Link Red Soial 1'),
        ),
        migrations.AddField(
            model_name='home',
            name='link_red_social2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Link Red Soial 2'),
        ),
        migrations.AddField(
            model_name='home',
            name='link_red_social3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Link Red Soial 3'),
        ),
        migrations.AddField(
            model_name='home',
            name='link_red_social4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Link Red Soial 4'),
        ),
        migrations.AddField(
            model_name='home',
            name='logo_red_social1',
            field=models.ImageField(blank=True, null=True, upload_to='Logos'),
        ),
        migrations.AddField(
            model_name='home',
            name='logo_red_social2',
            field=models.ImageField(blank=True, null=True, upload_to='Logos'),
        ),
        migrations.AddField(
            model_name='home',
            name='logo_red_social3',
            field=models.ImageField(blank=True, null=True, upload_to='Logos'),
        ),
        migrations.AddField(
            model_name='home',
            name='logo_red_social4',
            field=models.ImageField(blank=True, null=True, upload_to='Logos'),
        ),
        migrations.AddField(
            model_name='home',
            name='red_social1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Red Soial 1'),
        ),
        migrations.AddField(
            model_name='home',
            name='red_social2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Red Soial 2'),
        ),
        migrations.AddField(
            model_name='home',
            name='red_social3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Red Soial 3'),
        ),
        migrations.AddField(
            model_name='home',
            name='red_social4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Red Soial 4'),
        ),
    ]
