# Generated by Django 4.1.5 on 2023-02-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_home_face_remove_home_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='image_ours',
            field=models.ImageField(blank=True, null=True, upload_to='Portada'),
        ),
        migrations.AlterField(
            model_name='home',
            name='link_red_social1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Link Red Social 1'),
        ),
        migrations.AlterField(
            model_name='home',
            name='link_red_social2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Link Red Social 2'),
        ),
        migrations.AlterField(
            model_name='home',
            name='link_red_social3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Link Red Social 3'),
        ),
        migrations.AlterField(
            model_name='home',
            name='link_red_social4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Link Red Social 4'),
        ),
        migrations.AlterField(
            model_name='home',
            name='red_social1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Red Social 1'),
        ),
        migrations.AlterField(
            model_name='home',
            name='red_social2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Red Social 2'),
        ),
        migrations.AlterField(
            model_name='home',
            name='red_social3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Red Social 3'),
        ),
        migrations.AlterField(
            model_name='home',
            name='red_social4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Red Social 4'),
        ),
    ]
