# Generated by Django 4.1.5 on 2023-01-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='front_page',
        ),
        migrations.AlterField(
            model_name='entry',
            name='in_home',
            field=models.BooleanField(default=False, verbose_name='En home'),
        ),
    ]
