# Generated by Django 4.1.5 on 2023-01-30 16:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0003_remove_entry_front_page_alter_entry_in_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='resume',
            field=models.TextField(blank=True, null=True, verbose_name='Resumen'),
        ),
    ]
