# Generated by Django 4.1.5 on 2023-01-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0004_alter_entry_content_alter_entry_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='area_trabajo',
            field=models.BooleanField(default=False, verbose_name='area de trabajo'),
        ),
        migrations.AddField(
            model_name='entry',
            name='marcas',
            field=models.BooleanField(default=False, verbose_name='Es marca'),
        ),
    ]
