# Generated by Django 4.1.5 on 2023-01-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0005_entry_area_trabajo_entry_marcas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='marcas',
            field=models.BooleanField(default=False, verbose_name='En marca'),
        ),
    ]
