# Generated by Django 4.1.5 on 2023-01-30 14:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entrada', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Entradas_favoritas', to='entrada.entry')),
            ],
            options={
                'verbose_name_plural': 'Favoritos',
            },
        ),
    ]
